"""Добавил новую колонку с путём до фотографии

Revision ID: 09f1fbef4bdf
Revises: 965eccf898b0
Create Date: 2021-04-22 20:03:39.062415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f1fbef4bdf'
down_revision = '965eccf898b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_table', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_table', 'photo')
    # ### end Alembic commands ###
