"""Добавил адрес и телефон

Revision ID: 53fdfa2db1a3
Revises: 
Create Date: 2021-04-19 17:25:32.567527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53fdfa2db1a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('address', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'phone_number')
    op.drop_column('user_table', 'address')
    # ### end Alembic commands ###
