"""Добавил количество товара

Revision ID: 965eccf898b0
Revises: bd9717ffdb7e
Create Date: 2021-04-21 20:01:25.044758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965eccf898b0'
down_revision = 'bd9717ffdb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_table', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_table', 'amount')
    # ### end Alembic commands ###
