"""empty message

Revision ID: d9517f98cfe2
Revises: 09f1fbef4bdf
Create Date: 2021-04-25 18:09:22.089777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9517f98cfe2'
down_revision = '09f1fbef4bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
