"""empty message

Revision ID: eea8917f1e97
Revises: d9517f98cfe2
Create Date: 2021-04-25 18:10:06.357768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea8917f1e97'
down_revision = 'd9517f98cfe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
